//USER ACTIONS




//EVENT ACTIONS
export const EVENT_CREATED = "EVENT_CREATED";

// -Diplay Registered Events
export const DISPLAY_REGISTERED_EVENTS_REQ ="DISPLAY_REGISTERED_EVENTS_REQ";
export const DISPLAY_REGISTERED_EVENTS_SUCCESS ="DISPLAY_REGISTERED_EVENTS_SUCCESS";
export const DISPLAY_REGISTERED_EVENTS_FAILURE ="DISPLAY_REGISTERED_EVENTS_FAILURE";

// -Display Interested Events
export const DISPLAY_INTERESTED_EVENTS_REQ ="DISPLAY_INTERESTED_EVENTS_REQ";
export const DISPLAY_INTERESTED_EVENTS_SUCCESS ="DISPLAY_INTERESTED_EVENTS_SUCCESS";
export const DISPLAY_INTERESTED_EVENTS_FAILURE ="DISPLAY_INTERESTED_EVENTS_FAILURE";


