//USER ACTIONS
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

//general
export const HIDE_ALERT = "HIDE_ALERT";


//EVENT ACTIONS
export const EVENT_CREATE_SUCCESS = "EVENT_CREATE_SUCCESS";
export const EVENT_CREATE_FAILED = "EVENT_CREATE_FAILED";




// -Register for Event
export const EVENT_REGISTRATION_REQ ="EVENT_REGISTRATION_REQ";
export const EVENT_REGISTRATION_SUCCESS ="EVENT_REGISTRATION_SUCCESS";
export const EVENT_REGISTRATION_FAILURE ="EVENT_REGISTRATION_FAILURE";

// -Diplay Registered Events
export const DISPLAY_REGISTERED_EVENTS_REQ ="DISPLAY_REGISTERED_EVENTS_REQ";
export const DISPLAY_REGISTERED_EVENTS_SUCCESS ="DISPLAY_REGISTERED_EVENTS_SUCCESS";
export const DISPLAY_REGISTERED_EVENTS_FAILURE ="DISPLAY_REGISTERED_EVENTS_FAILURE";

// -Add Event to Interested Events
export const EVENT_INTERESTED_REQ ="EVENT_INTERESTED_REQ";
export const EVENT_INTERESTED_SUCCESS ="EVENT_INTERESTED_SUCCESS";
export const EVENT_INTERESTED_FAILURE ="EVENT_INTERESTED_FAILURE";

// -Display Interested Events
export const DISPLAY_INTERESTED_EVENTS_REQ ="DISPLAY_INTERESTED_EVENTS_REQ";
export const DISPLAY_INTERESTED_EVENTS_SUCCESS ="DISPLAY_INTERESTED_EVENTS_SUCCESS";
export const DISPLAY_INTERESTED_EVENTS_FAILURE ="DISPLAY_INTERESTED_EVENTS_FAILURE";

// -POST COMMENT
export const POST_COMMENT_REQ="POST_COMMENT_REQ";
export const POST_COMMENT_SUCCESS="POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE="POST_COMMENT_FAILURE";




// -DISPLAY COMMENTS
export const DISPLAY_COMMENTS_REQ="DISPLAY_COMMENTS_REQ";
export const DISPLAY_COMMENTS_SUCCESS="DISPLAY_COMMENTS_SUCCESS";
export const DISPLAY_COMMENTS_FAILURE="DISPLAY_COMMENTS_FAILURE";



// -----------------OC Actions---------------

export const LOADING = "LOADING";
export const ALL_OC_FETCHED = "ALL_OC_FETCHED";
export const SELECT_OC = "SELECT_OC";

export const HIDE_OC_ALERT = "HIDE_OC_ALERT";

export const FOLLOW_REQUEST_ACCEPTED = "FOLLOW_REQUEST_ACCEPTED";
export const FOLLOW_REQUEST_DENIED = "FOLLOW_REQUEST_DENIED";

export const UNFOLLOW_REQUEST_ACCEPTED = "UNFOLLOW_REQUEST_ACCEPTED";
export const UNFOLLOW_REQUEST_DENIED = "UNFOLLOW_REQUEST_DENIED";

export const FETCHED_OC = "FETCHED_OC";

export const MEMBER_REQUEST_SENT = "MEMBER_REQUEST_SENT";

export const MEMBER_REQUEST_EXISTS = "MEMBER_REQUEST_EXISTS";
export const MEMBER_REQUEST_NOT_EXISTS = "MEMBER_REQUEST_NOT_EXISTS";

