//USER ACTIONS




//EVENT ACTIONS
export const EVENT_CREATED = "EVENT_CREATED";

// -Register for Event
export const EVENT_REGISTRATION_REQ ="EVENT_REGISTRATION_REQ";
export const EVENT_REGISTRATION_SUCCESS ="EVENT_REGISTRATION_SUCCESS";
export const EVENT_REGISTRATION_FAILURE ="EVENT_REGISTRATION_FAILURE";

// -Diplay Registered Events
export const DISPLAY_REGISTERED_EVENTS_REQ ="DISPLAY_REGISTERED_EVENTS_REQ";
export const DISPLAY_REGISTERED_EVENTS_SUCCESS ="DISPLAY_REGISTERED_EVENTS_SUCCESS";
export const DISPLAY_REGISTERED_EVENTS_FAILURE ="DISPLAY_REGISTERED_EVENTS_FAILURE";

// -Add Event to Interested Events
export const EVENT_INTERESTED_REQ ="EVENT_INTERESTED_REQ";
export const EVENT_INTERESTED_SUCCESS ="EVENT_INTERESTED_SUCCESS";
export const EVENT_INTERESTED_FAILURE ="EVENT_INTERESTED_FAILURE";

// -Display Interested Events
export const DISPLAY_INTERESTED_EVENTS_REQ ="DISPLAY_INTERESTED_EVENTS_REQ";
export const DISPLAY_INTERESTED_EVENTS_SUCCESS ="DISPLAY_INTERESTED_EVENTS_SUCCESS";
export const DISPLAY_INTERESTED_EVENTS_FAILURE ="DISPLAY_INTERESTED_EVENTS_FAILURE";

// -POST COMMENT
export const POST_COMMENT_REQ="POST_COMMENT_REQ";
export const POST_COMMENT_SUCCESS="POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE="POST_COMMENT_FAILURE";